import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";
import { Outfit } from "next/font/google";
import ReactQueryProvider from "@/lib/ReactQueryProvider";
import ClientWrapper from "./ClientWrapper";

const outfit = Outfit({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-outfit",
});

export const metadata: Metadata = {
    title: "Wellness",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="es">
            <body
                suppressHydrationWarning={true}
                className={`${outfit.variable || ""} font-outfit h-[100vh]`}
            >
                <ReactQueryProvider>
                    <ClientWrapper>
                        <Navbar />
                        {children}
                    </ClientWrapper>
                </ReactQueryProvider>
            </body>
        </html>
    );
}
